//! Central registry of agent tools with schema and execution metadata.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ToolKind {
    Read,
    Write,
}

/// Execution mode for tool dispatch.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ExecutionMode {
    /// Execute immediately; no user approval.
    ReadAuto,
    /// Must wait for user approval before execution.
    ApprovalRequired,
}

#[derive(Debug, Clone)]
#[allow(dead_code)]
pub struct ToolDef {
    pub name: &'static str,
    pub kind: ToolKind,
    pub description: &'static str,
    pub parameters: &'static str, // JSON Schema string
    pub execution_mode: ExecutionMode,
    pub requires_wallet: bool,
    pub supports_multi_wallet: bool,
    pub supports_synthesis: bool,
    pub example: &'static str,
    /// Bundled app id when this tool is gated (`None` = always available).
    pub required_app_id: Option<&'static str>,
    /// Subset of manifest permission ids that must be granted in SQLite.
    pub required_permission_ids: &'static [&'static str],
}

pub fn all_tools() -> Vec<ToolDef> {
    vec![
        ToolDef {
            name: "get_wallet_balances",
            kind: ToolKind::Read,
            description: "Get all token balances across connected chains.",
            parameters: r#"{"type": "object", "properties": {}}"#,
            execution_mode: ExecutionMode::ReadAuto,
            requires_wallet: true,
            supports_multi_wallet: true,
            supports_synthesis: true,
            example: "get_wallet_balances()",
            required_app_id: None,
            required_permission_ids: &[],
        },
        ToolDef {
            name: "get_total_portfolio_value",
            kind: ToolKind::Read,
            description: "Get total portfolio value in USD and per-token breakdown.",
            parameters: r#"{"type": "object", "properties": {}}"#,
            execution_mode: ExecutionMode::ReadAuto,
            requires_wallet: true,
            supports_multi_wallet: true,
            supports_synthesis: true,
            example: "get_total_portfolio_value()",
            required_app_id: None,
            required_permission_ids: &[],
        },
        ToolDef {
            name: "get_token_price",
            kind: ToolKind::Read,
            description: "Get current USD price for a token symbol.",
            parameters: r#"{"type": "object", "properties": {"tokenSymbol": {"type": "string", "description": "e.g. ETH, BTC, USDC"}}, "required": ["tokenSymbol"]}"#,
            execution_mode: ExecutionMode::ReadAuto,
            requires_wallet: false,
            supports_multi_wallet: false,
            supports_synthesis: true,
            example: "get_token_price(tokenSymbol=ETH)",
            required_app_id: None,
            required_permission_ids: &[],
        },
        ToolDef {
            name: "web_research",
            kind: ToolKind::Read,
            description: "Search the web for real-time market news, catalysts, or project details. Use this for up-to-date intelligence.",
            parameters: r#"{"type": "object", "properties": {"query": {"type": "string", "description": "Search query"}}, "required": ["query"]}"#,
            execution_mode: ExecutionMode::ReadAuto,
            requires_wallet: false,
            supports_multi_wallet: false,
            supports_synthesis: true,
            example: "web_research(query=\"Ethereum price action catalysts this week\")",
            required_app_id: None,
            required_permission_ids: &[],
        },
        ToolDef {
            name: "analyze_portfolio_history",
            kind: ToolKind::Read,
            description: "Fetch historical portfolio snapshots to analyze performance, TWR, and PnL trends.",
            parameters: r#"{"type": "object", "properties": {"limit": {"type": "integer", "description": "Number of recent snapshots to fetch", "default": 10}}}"#,
            execution_mode: ExecutionMode::ReadAuto,
            requires_wallet: true,
            supports_multi_wallet: true,
            supports_synthesis: true,
            example: "analyze_portfolio_history(limit=5)",
            required_app_id: None,
            required_permission_ids: &[],
        },
        ToolDef {
            name: "execute_token_swap",
            kind: ToolKind::Write,
            description: "Swap one token for another. Requires user approval.",
            parameters: r#"{"type": "object", "properties": {"fromToken": {"type": "string"}, "toToken": {"type": "string"}, "amount": {"type": "string"}, "chain": {"type": "string"}, "slippage": {"type": "number"}}, "required": ["fromToken", "toToken", "amount", "chain"]}"#,
            execution_mode: ExecutionMode::ApprovalRequired,
            requires_wallet: true,
            supports_multi_wallet: false,
            supports_synthesis: false,
            example: "execute_token_swap(fromToken=USDC, toToken=ETH, amount=100, chain=ETH)",
            required_app_id: None,
            required_permission_ids: &[],
        },
        ToolDef {
            name: "create_automation_strategy",
            kind: ToolKind::Write,
            description: "Create a persistent autonomous strategy (DCA, rebalance, arbitrage). Requires trigger, action, and guardrails config.",
            parameters: r#"{"type": "object", "properties": {"name": {"type": "string"}, "summary": {"type": "string"}, "trigger": {"type": "object", "description": "e.g. {type: 'time', interval: '1week'}"}, "action": {"type": "object", "description": "e.g. {type: 'swap', from: 'ETH', to: 'USDC', amount: '0.1'}"}, "guardrails": {"type": "object"}}, "required": ["name", "trigger", "action", "guardrails"]}"#,
            execution_mode: ExecutionMode::ApprovalRequired,
            requires_wallet: true,
            supports_multi_wallet: false,
            supports_synthesis: false,
            example: "create_automation_strategy(name=\"Weekly ETH DCA\", trigger={type: 'time', interval: '1week'}, action={type: 'swap', from: 'USDC', to: 'ETH', amount: '100'}, guardrails={maxSlippage: 0.5})",
            required_app_id: None,
            required_permission_ids: &[],
        },
        ToolDef {
            name: "calculate_portfolio_drift",
            kind: ToolKind::Read,
            description: "Compare current portfolio against target allocations to identify overweight/underweight assets.",
            parameters: r#"{"type": "object", "properties": {"targetAllocations": {"type": "array", "items": {"type": "object", "properties": {"symbol": {"type": "string"}, "percentage": {"type": "number"}}}}}}"#,
            execution_mode: ExecutionMode::ReadAuto,
            requires_wallet: true,
            supports_multi_wallet: true,
            supports_synthesis: true,
            example: "calculate_portfolio_drift(targetAllocations=[{symbol: 'ETH', percentage: 50}, {symbol: 'USDC', percentage: 50}])",
            required_app_id: None,
            required_permission_ids: &[],
        },
        ToolDef {
            name: "build_emergency_eject_route",
            kind: ToolKind::Read,
            description: "Calculate optimal panic exit routes for specific assets to safe-havens like USDC or Cold Storage.",
            parameters: r#"{"type": "object", "properties": {"assets": {"type": "array", "items": {"type": "string"}}, "destination": {"type": "string", "default": "USDC"}}, "required": ["assets"]}"#,
            execution_mode: ExecutionMode::ReadAuto,
            requires_wallet: true,
            supports_multi_wallet: true,
            supports_synthesis: true,
            example: "build_emergency_eject_route(assets=[\"ETH\", \"ARB\"], destination=\"USDC\")",
            required_app_id: None,
            required_permission_ids: &[],
        },
        ToolDef {
            name: "list_automation_strategies",
            kind: ToolKind::Read,
            description: "Returns a list of all current automation strategies and their status (active/paused).",
            parameters: r#"{"type": "object", "properties": {}}"#,
            execution_mode: ExecutionMode::ReadAuto,
            requires_wallet: false,
            supports_multi_wallet: false,
            supports_synthesis: true,
            example: "list_automation_strategies()",
            required_app_id: None,
            required_permission_ids: &[],
        },
        ToolDef {
            name: "update_automation_strategy_status",
            kind: ToolKind::Write,
            description: "Updates the status of an existing automation strategy. Use this to pause, resume (active), or stop strategies.",
            parameters: r#"{"type": "object", "properties": {"id": {"type": "string"}, "status": {"type": "string", "enum": ["active", "paused"]}}, "required": ["id", "status"]}"#,
            execution_mode: ExecutionMode::ReadAuto, // Agent can do this immediately
            requires_wallet: false,
            supports_multi_wallet: false,
            supports_synthesis: false,
            example: "update_automation_strategy_status(id=\"uuid-123\", status=\"paused\")",
            required_app_id: None,
            required_permission_ids: &[],
        },
        ToolDef {
            name: "lit_protocol_wallet_status",
            kind: ToolKind::Read,
            description: "Requires Lit app. Read Lit/Vincent-shaped agent wallet status and configured guardrails (install Lit in Apps if missing).",
            parameters: r#"{"type": "object", "properties": {"dailyLimitUsd": {"type": "number"}}}"#,
            execution_mode: ExecutionMode::ReadAuto,
            requires_wallet: false,
            supports_multi_wallet: false,
            supports_synthesis: true,
            example: "lit_protocol_wallet_status()",
            required_app_id: Some("lit-protocol"),
            required_permission_ids: &["agent_wallet.manage", "network.lit"],
        },
        ToolDef {
            name: "lit_protocol_precheck_action",
            kind: ToolKind::Read,
            description: "Requires Lit app. Precheck a proposed action against Lit guardrails before execution.",
            parameters: r#"{"type": "object", "properties": {"kind": {"type": "string"}, "notionalUsd": {"type": "number"}}, "required": ["kind"]}"#,
            execution_mode: ExecutionMode::ReadAuto,
            requires_wallet: false,
            supports_multi_wallet: false,
            supports_synthesis: true,
            example: "lit_protocol_precheck_action(kind=\"swap\", notionalUsd=250)",
            required_app_id: Some("lit-protocol"),
            required_permission_ids: &["execution.precheck", "network.lit"],
        },
        ToolDef {
            name: "lit_protocol_connect_wallet",
            kind: ToolKind::Write,
            description: "Requires Lit app. Create or refresh the Lit PKP agent wallet session. Mints a new PKP if none exists.",
            parameters: r#"{"type": "object", "properties": {"memo": {"type": "string"}}}"#,
            execution_mode: ExecutionMode::ReadAuto,
            requires_wallet: false,
            supports_multi_wallet: false,
            supports_synthesis: false,
            example: "lit_protocol_connect_wallet()",
            required_app_id: Some("lit-protocol"),
            required_permission_ids: &["agent_wallet.manage", "network.lit"],
        },
        ToolDef {
            name: "lit_protocol_execute_swap",
            kind: ToolKind::Write,
            description: "Requires Lit app. Execute a token swap through the Lit PKP agent wallet with decentralized policy enforcement. Requires user approval.",
            parameters: r#"{"type": "object", "properties": {"fromToken": {"type": "string"}, "toToken": {"type": "string"}, "amountUsd": {"type": "number"}, "chain": {"type": "string"}, "protocol": {"type": "string", "default": "uniswap"}}, "required": ["fromToken", "toToken", "amountUsd"]}"#,
            execution_mode: ExecutionMode::ApprovalRequired,
            requires_wallet: true,
            supports_multi_wallet: false,
            supports_synthesis: false,
            example: "lit_protocol_execute_swap(fromToken=\"USDC\", toToken=\"ETH\", amountUsd=20, chain=\"ethereum\", protocol=\"uniswap\")",
            required_app_id: Some("lit-protocol"),
            required_permission_ids: &["agent_wallet.manage", "execution.precheck", "network.lit"],
        },
        ToolDef {
            name: "flow_protocol_account_status",
            kind: ToolKind::Read,
            description: "Requires Flow app. Read Flow account connectivity for sponsored transaction flows.",
            parameters: r#"{"type": "object", "properties": {}}"#,
            execution_mode: ExecutionMode::ReadAuto,
            requires_wallet: false,
            supports_multi_wallet: false,
            supports_synthesis: true,
            example: "flow_protocol_account_status()",
            required_app_id: Some("flow"),
            required_permission_ids: &["flow.account.read", "network.flow"],
        },
        ToolDef {
            name: "flow_protocol_prepare_sponsored_transaction",
            kind: ToolKind::Write,
            description: "Requires Flow app. Prepare a sponsored Flow transaction for user approval (SHADOW schedules recurring runs separately).",
            parameters: r#"{"type": "object", "properties": {"summary": {"type": "string"}, "cadenceNote": {"type": "string"}}, "required": ["summary"]}"#,
            execution_mode: ExecutionMode::ApprovalRequired,
            requires_wallet: false,
            supports_multi_wallet: false,
            supports_synthesis: false,
            example: "flow_protocol_prepare_sponsored_transaction(summary=\"Monthly reserve transfer\", cadenceNote=\"SHADOW scheduler\")",
            required_app_id: Some("flow"),
            required_permission_ids: &["flow.tx.prepare", "network.flow"],
        },
        ToolDef {
            name: "filecoin_protocol_list_backups",
            kind: ToolKind::Read,
            description: "Requires Filecoin app. List stored backup CIDs and metadata.",
            parameters: r#"{"type": "object", "properties": {"limit": {"type": "integer", "default": 20}}}"#,
            execution_mode: ExecutionMode::ReadAuto,
            requires_wallet: false,
            supports_multi_wallet: false,
            supports_synthesis: true,
            example: "filecoin_protocol_list_backups(limit=10)",
            required_app_id: Some("filecoin-storage"),
            required_permission_ids: &["backup.read_local_state"],
        },
        ToolDef {
            name: "filecoin_protocol_request_backup",
            kind: ToolKind::Write,
            description: "Requires Filecoin app. Request encrypted backup of agent memory/config scope (requires approval).",
            parameters: r#"{"type": "object", "properties": {"includeAgentMemory": {"type": "boolean"}, "includePersona": {"type": "boolean"}}, "required": ["includeAgentMemory"]}"#,
            execution_mode: ExecutionMode::ApprovalRequired,
            requires_wallet: false,
            supports_multi_wallet: false,
            supports_synthesis: false,
            example: "filecoin_protocol_request_backup(includeAgentMemory=true, includePersona=false)",
            required_app_id: Some("filecoin-storage"),
            required_permission_ids: &["backup.read_local_state", "network.filecoin"],
        },
        ToolDef {
            name: "filecoin_protocol_request_restore",
            kind: ToolKind::Write,
            description: "Requires Filecoin app. Request restore from a CID (requires approval).",
            parameters: r#"{"type": "object", "properties": {"cid": {"type": "string"}}, "required": ["cid"]}"#,
            execution_mode: ExecutionMode::ApprovalRequired,
            requires_wallet: false,
            supports_multi_wallet: false,
            supports_synthesis: false,
            example: "filecoin_protocol_request_restore(cid=\"bafy...\")",
            required_app_id: Some("filecoin-storage"),
            required_permission_ids: &["network.filecoin"],
        },
        ToolDef {
            name: "apps_schedule_integration_job",
            kind: ToolKind::Write,
            description: "Requires target app. Register a SHADOW scheduler job for Flow recurring prepare or Filecoin auto-backup (interval seconds, JSON payload).",
            parameters: r#"{"type": "object", "properties": {"appId": {"type": "string"}, "kind": {"type": "string", "enum": ["flow_recurring_prepare", "filecoin_autobackup"]}, "intervalSeconds": {"type": "integer"}, "payload": {"type": "object"}}, "required": ["appId", "kind", "intervalSeconds", "payload"]}"#,
            execution_mode: ExecutionMode::ReadAuto,
            requires_wallet: false,
            supports_multi_wallet: false,
            supports_synthesis: false,
            example: "apps_schedule_integration_job(appId=\"flow\", kind=\"flow_recurring_prepare\", intervalSeconds=604800, payload={\"summary\":\"Weekly\"})",
            required_app_id: None,
            required_permission_ids: &[],
        },
    ]
}
